/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary':                '#545f73',
        'on-secondary':             '#ffffff',
        'on-error-container':       '#93000a',
        'secondary-container':      '#d5e0f8',
        'on-secondary-container':   '#586377',
        'outline-variant':          '#bccabb',
        'outline':                  '#6d7b6d',
        'on-tertiary':              '#ffffff',
        'error-container':          '#ffdad6',
        'surface':                  '#f8f9ff',
        'surface-bright':           '#f8f9ff',
        'primary':                  '#006d36',
        'on-primary':               '#ffffff',
        'primary-container':        '#4ade80',
        'on-primary-container':     '#005e2d',
        'surface-container-low':    '#eff4ff',
        'surface-container-lowest': '#ffffff',
        'surface-container':        '#e5eeff',
        'surface-container-high':   '#dce9ff',
        'surface-container-highest':'#d3e4fe',
        'surface-variant':          '#d3e4fe',
        'surface-dim':              '#cbdbf5',
        'tertiary':                 '#006591',
        'tertiary-container':       '#83ccff',
        'on-tertiary-container':    '#00567d',
        'on-surface-variant':       '#3d4a3e',
        'on-background':            '#0b1c30',
        'on-surface':               '#0b1c30',
        'on-error':                 '#ffffff',
        'error':                    '#ba1a1a',
        'inverse-primary':          '#4de082',
        'inverse-surface':          '#213145',
        'background':               '#f8f9ff',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg:      '2rem',
        xl:      '3rem',
        full:    '9999px',
      },
      spacing: {
        xs:   '4px',
        sm:   '8px',
        md:   '16px',
        lg:   '24px',
        xl:   '32px',
        xxl:  '48px',
      },
      fontSize: {
        'label-md':           ['12px',  { lineHeight: '16px',  fontWeight: '600', letterSpacing: '0.05em' }],
        'body-sm':            ['14px',  { lineHeight: '20px',  fontWeight: '400' }],
        'body-md':            ['16px',  { lineHeight: '24px',  fontWeight: '400' }],
        'body-lg':            ['18px',  { lineHeight: '28px',  fontWeight: '400' }],
        'headline-sm':        ['20px',  { lineHeight: '28px',  fontWeight: '600' }],
        'headline-md':        ['24px',  { lineHeight: '32px',  fontWeight: '600' }],
        'headline-lg':        ['32px',  { lineHeight: '40px',  fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-lg-mobile': ['28px',  { lineHeight: '36px',  fontWeight: '600' }],
        'display-lg':         ['48px',  { lineHeight: '56px',  fontWeight: '700', letterSpacing: '-0.02em' }],
      },
    },
  },
  plugins: [],
}
